export default {
  "login": "cleverNishanth",
  "id": 75757846,
  "node_id": "MDQ6VXNlcjc1NzU3ODQ2",
  "avatar_url": "https://avatars.githubusercontent.com/u/75757846?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cleverNishanth",
  "html_url": "https://github.com/cleverNishanth",
  "followers_url": "https://api.github.com/users/cleverNishanth/followers",
  "following_url": "https://api.github.com/users/cleverNishanth/following{/other_user}",
  "gists_url": "https://api.github.com/users/cleverNishanth/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cleverNishanth/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cleverNishanth/subscriptions",
  "organizations_url": "https://api.github.com/users/cleverNishanth/orgs",
  "repos_url": "https://api.github.com/users/cleverNishanth/repos",
  "events_url": "https://api.github.com/users/cleverNishanth/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cleverNishanth/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Nishanth",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "React JS developer.\r\nB.Tech Information Technology Student...",
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2020-12-09T21:09:12Z",
  "updated_at": "2021-06-04T20:51:21Z"
}
